### PR TITLE
Syncing changes from the old AFS git repo

### PR DESCRIPTION
**Pull request by ddamiani**
I noticed that there were commits in the AFS git repo of ADAndor that aren't on github.

Main changes:

- Added support for a new camera model: iXonUltra888 -> UED is using this.
- Updated the version of the Andor SDK - this was needed for the above camera.
- In the SDK update ShamrockCIF.h -> atspectrograph.h and all the functions defined in the header went from Shamrock<funcname> to ATSpectrograph<funcname>
- Added PV for setting the HighCapacity feature on ccds that support it.
- BaselineClamp is not actually supported by all ccds, so the code now checks if the camera has the baselineclamp feature

### CODE REVIEW

**Comment by JJL772** [comment]
Thanks for syncing these. I'll mark the ADVimba repository on AFS as read-only to prevent these issues in the future, if that's okay with you.

**Comment by ddamiani** [comment]
Yes please set it to read! Thank you!

**Comment by JJL772** [comment]
Alright, I've marked it read-only. This is what appears when you attempt to push to it:
```
$ git push -u origin test 
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 
remote: 
remote: NOTICE: This repository has been moved to https://github.com/slac-epics/ADAndor.git
remote: 
remote: Pushes here are no longer accepted, please update your remote with:
remote: git remote set-url origin git@github.com:slac-epics/ADAndor.git
remote: 
remote: 
To /afs/slac/g/cd/swe/git/repos/package/epics/modules/ADAndor.git
 ! [remote rejected] test -> test (pre-receive hook declined)
error: failed to push some refs to '/afs/slac/g/cd/swe/git/repos/package/epics/modules/ADAndor.git'
```

**Review by JJL772 — APPROVED** [review]
@marciodo do you want to have a once-over too?

**Pull request merged**
